[package]
name = "timely_communication"
version = "0.1.8"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "Communication layer for timely dataflow"

# These URLs point to more information about the repository
documentation = "https://frankmcsherry.github.com/timely-dataflow"
homepage = "https://github.com/frankmcsherry/timely-dataflow"
repository = "https://github.com/frankmcsherry/timely-dataflow.git"
keywords = ["timely", "dataflow"]
license = "MIT"

[features]
default=[] # ["logging"]

[dependencies]
byteorder="0.4.2"
getopts="0.2.14"
time="0.1.34"
abomonation = { git = "https://github.com/frankmcsherry/abomonation" }
abomonation_derive = { git = "https://github.com/mystor/abomonation_derive.git" }

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
