[package]

name = "timely"
version = "0.3.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "A low-latency data-parallel dataflow system in Rust"

# These URLs point to more information about the repository
documentation = "https://frankmcsherry.github.com/timely-dataflow"
homepage = "https://github.com/frankmcsherry/timely-dataflow"
repository = "https://github.com/frankmcsherry/timely-dataflow.git"
keywords = ["timely", "dataflow"]
license = "MIT"

#build = "booktests.rs"

[features]
default=[]

[dependencies]
abomonation = { git = "https://github.com/frankmcsherry/abomonation" }
abomonation_derive = { git = "https://github.com/mystor/abomonation_derive.git" }
timely_sort="0.1.6"
timely_communication = { version = "0.1.8", path = "./communication" }
byteorder="0.4.2"
time="0.1.34"

[dev-dependencies]
getopts="0.2.14"
rand="0.3.13"
#skeptic = "0.12"

#[build-dependencies]
#skeptic = "0.12"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
